PATTERNS = {
    "password_assignment": r"password\s*[:=]\s*\S+",
    "weak_password": r"(password123|admin123|123456|qwerty|letmein)",
    "token_assignment": r"token\s*[:=]\s*\S+",
    "api_key_assignment": r"api[_\s]?key\s*[:=]\s*\S+",
    "email": r"\S+@\S+\.\S+",
    "aws_key": r"AKIA[0-9A-Z]{16}",
    "github_token": r"ghp_[A-Za-z0-9]{10}",
    "bearer_token": r"Bearer\s+[A-Za-z0-9\-\.]+",
    "ip_address": r"\b(?:\d{1,3}\.){3}\d{1,3}\b",
    "sql_injection_payload": r"('|--|;|OR\s+1=1|UNION\s+SELECT)",
    "jwt_token": r"eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+",
    "api_endpoint": r"/api/[A-Za-z0-9_\-/]+",
    "admin_endpoint": r"/admin/[A-Za-z0-9_\-/]*",
    "debug_endpoint": r"/debug/[A-Za-z0-9_\-/]*",
    "authorization_header": r"Authorization:\s*(Bearer|Basic)\s+[A-Za-z0-9\-_.:=]+",
    "default_credentials": r"(admin|root|test|guest)[:=](admin|root|password|123456)",
    "basic_auth": r"Basic\s+[A-Za-z0-9+/=]+",
    "login_bypass": r"('|\"|\-\-|\#)\s*(OR|or)\s*1=1",
    "hardcore_login": r"(username|user|login)\s*[:=]\s*['\"][A-Za-z0-9_]+['\"]",
    "eval_usage": r"eval\s*\(",
    "exec_usage": r"exec\s*\(",
    "os_system_usage": r"os\.system\s*\(",
    "subprocess_usage": r"subprocess\.(Popen|run|call)\s*\(",
    "pickle_loads": r"pickle\.loads\s*\(",
    "powershell": r"(powershell|powershell\.exe|Invoke-WebRequest|ExecutionPolicy\s+Bypass)",
    "base64_payload": r"[A-Za-z0-9+/]{40,}={0,2}",
    "download_activity": r"(curl\s+http|wget\s+http|Imvoke-WebReuest\s+http)",
    "reverse_shell": r"(bash\s+-i|nc\s+-e|netcat|/bin/sh|/bin/bash|python\s+-c)",
    "reverse_shell": r"nc\s+-e|bash\s+-i|/bin/sh|/bin/bash",
    "powershell": r"powershell\.exe|powershell\s",
    "download_activity": r"curl\s+http|wget\s+http|Invoke-WebRequest",
    "os_system": r"os\.system\(",
    "xss": r"(<scripts>|javascript:|onerror=|onload=|alert\s*\()"
}

