PATTERN_SEVERITY_MAP = {
    "email": "LOW",
    "password_assignment": "HIGH",
    "weak_password": "HIGH",
    "token_assignment": "HIGH",
    "api_key_assignment": "HIGH",
    "aws_key": "HIGH",
    "github_token": "HIGH",
    "bearer_token": "HIGH",
    "ip_address": "LOW",
    "aws_key": "HIGH",
    "github_token": "HIGH",
    "bearer_token": "HIGH",
    "sql_injection_payload": "HIGH",
    "jwt_token": "HIGH",
    "api_endpoint": "LOW",
    "admin_endpoint": "HIGH",
    "debug_endpoint": "MEDIUM",
    "authorization_header": "HIGH",
    "default_credentials": "HIGH",
    "basic_auth": "HIGH",
    "login_bypass": "HIGH",
    "hardcoded_login": "MEDIUM",
    "eval_usage": "HIGH",
    "exec_usage": "HIGH",
    "os_system_usage": "HIGH",
    "subprocess_usage": "MEDIUM",
    "pickle_loads": "HIGH",
    "powershell": "HIGH",
    "base64_payload": "MEDIUM",
    "download_activity": "HIGH",
    "reverse_shell": "HIGH",
    "reverse_shell": "HIGH",
    "powershell": "HIGH",
    "download_activity": "HIGH",
    "os_system": "HIGH",
}

def classify_severity(pattern_name):
        return PATTERN_SEVERITY_MAP.get(pattern_name, "MEDIUM")